server:
  port: 38080

logging:
  level:
    io.github.vcvitaly: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

spring:
  datasource:
    url: jdbc:postgresql://${JPA_PLAYGROUND_DB_HOST:localhost}:${JPA_PLAYGROUND_DB_PORT:5432}/${JPA_PLAYGROUND_DB_NAME:jpa_playground}?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: local
