server:
  port: 38080

logging:
  level:
    io.github.vcvitaly: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_playground?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: local
